name: hanoman
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^13.0.0
  hooks_riverpod: ^2.4.9
  responsive_framework: ^1.1.1
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:

  uses-material-design: true

  assets:
    - assets/
